Subset covariance matrix to samples in sample.id if specified
smgogarten/GENESIS pull request #78
Opened 2021-10-11 20:18 UTC by amstilp

* When fitting a null model with an AnnotatedDataFrame, `fitNullModel` will subset `cov.mat` to the samples specified in `sample.id` before checking for consistency with `x`.
* Add a unit test for this behavior

Is this too confusing of a change to make?

2021-10-11 20:20 UTC, amstilp commented on R/fitNullModel.R
> +
The only real change in this function is to move this check after the subsetting by `sample.id`.

2021-10-13 18:21 UTC, smgogarten requested changes
If we don't have one already, we need a unit test for the case when `sample.id` is provided AND `cov.mat` is missing row and column names, as I suspect that could fail in the new code. We might need to split up the two checks in `checkSampleId` so one happens before the `sample.id` code block and the other happens after.

2021-10-13 18:21 UTC, smgogarten commented on R/fitNullModel.R
> +
Will this still work if `cov.mat` does not have rownames and colnames specified correctly (which `.checkSampleId` previously ensured)?

2021-10-20 22:34 UTC, amstilp commented on R/fitNullModel.R
> +
It does still work, but the reason isn't intuitive from just looking at the code. I think the covariance matrix gets subset to a zero by zero matrix when attempting to subset by sample id. Splitting the check into two makes more sense.

2021-10-20 22:36 UTC, amstilp commented
I'm still wondering if it makes more sense to require that all samples in `x` are in the covariance matrix (unless a `sample.id` argument is passed). It would require people calling `fitNullModel` with a `SeqVarData` (or iterator) object to explicitly set `sample.id`, but that's less confusing to me than specifying the set of samples by the rownames/colnames of the covariance matrix.

2021-10-21 16:35 UTC, amstilp commented
I ended up making the change to require `cov.mat` to have all samples in `x` unless `sample.id` is passed. We can choose not to keep it if it's not the desired behavior.

2021-10-21 16:59 UTC, smgogarten commented
I agree that it makes more sense this way. I'm going to merge this and get it in Bioconductor for the next release (deadline is tomorrow).

2021-10-21 17:00 UTC, merged